package autohome;

import javafx.embed.swing.SwingFXUtils;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.control.ScrollPane;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.image.WritableImage;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.VBox;
import javafx.stage.FileChooser;
import javafx.stage.Stage;

import javax.imageio.ImageIO;
import java.io.File;
import java.io.IOException;

public class ReportGenerator {
    public static String saveBlueprintImage(Stage stage, WritableImage snapshot) {
        FileChooser fileChooser = new FileChooser();
        fileChooser.setTitle("Save Blueprint Image");
        fileChooser.getExtensionFilters().add(new FileChooser.ExtensionFilter("PNG files", "*.png"));
        File file = fileChooser.showSaveDialog(stage);
        if (file != null) {
            try {
                saveImage(snapshot, file);
                return file.getAbsolutePath();
            } catch (IOException e) {
                e.printStackTrace();
                return null;
            }
        }
        return null;
    }

    public static void saveImage(WritableImage image, File file) throws IOException {
        ImageIO.write(SwingFXUtils.fromFXImage(image, null), "png", file);
    }

    public static void generateReport(Stage stage, int bedrooms, int bathrooms, int kitchens,
                                      boolean hasGarden, String blueprintPath, String userName, String userRole) {
        Stage reportStage = new Stage();
        reportStage.setTitle("House Design Report");

        VBox reportContent = new VBox(20);
        reportContent.setPadding(new javafx.geometry.Insets(20));
        reportContent.setStyle("-fx-background-color: white;");

        Label title = new Label("House Design Report");
        title.setStyle("-fx-font-size: 24px; -fx-font-weight: bold;");

        VBox specsBox = new VBox(10);
        specsBox.setPadding(new javafx.geometry.Insets(10));
        specsBox.setStyle("-fx-background-color: #f8f8f8; -fx-border-color: #e0e0e0; -fx-border-width: 1; -fx-border-radius: 5;");

        Label specsTitle = new Label("Floor Plan Specifications");
        specsTitle.setStyle("-fx-font-size: 20px; -fx-font-weight: bold; -fx-underline: true;");

        GridPane specsGrid = new GridPane();
        specsGrid.setHgap(10);
        specsGrid.setVgap(5);
        specsGrid.addRow(0, new Label("Bedrooms:"), new Label(String.valueOf(bedrooms)));
        specsGrid.addRow(1, new Label("Bathrooms:"), new Label(String.valueOf(bathrooms)));
        specsGrid.addRow(2, new Label("Kitchens:"), new Label(String.valueOf(kitchens)));
        specsGrid.addRow(3, new Label("Garden:"), new Label(hasGarden ? "Yes" : "No"));
        specsGrid.addRow(4, new Label("User:"), new Label(userName + " (" + userRole + ")"));

        specsBox.getChildren().addAll(specsTitle, specsGrid);

        VBox blueprintBox = new VBox(10);
        blueprintBox.setPadding(new javafx.geometry.Insets(10));
        blueprintBox.setStyle("-fx-background-color: #f8f8f8; -fx-border-color: #e0e0e0; -fx-border-width: 1; -fx-border-radius: 5;");

        Label blueprintTitle = new Label("Blueprint Design");
        blueprintTitle.setStyle("-fx-font-size: 20px; -fx-font-weight: bold; -fx-underline: true;");

        ImageView blueprintView = new ImageView();
        blueprintView.setPreserveRatio(true);
        blueprintView.setFitWidth(550);

        if (blueprintPath != null && !blueprintPath.isEmpty()) {
            File imageFile = new File(blueprintPath);
            if (imageFile.exists()) {
                Image image = new Image(imageFile.toURI().toString());
                blueprintView.setImage(image);
            } else {
                blueprintView.setImage(createPlaceholderImage());
            }
        } else {
            blueprintView.setImage(createPlaceholderImage());
        }

        blueprintBox.getChildren().addAll(blueprintTitle, blueprintView);

        Label footer = new Label("Generated by SnapPlan Pro Lite - Autohome Designer\n© 2025 Autohome Inc. All rights reserved.");
        footer.setStyle("-fx-font-size: 14px; -fx-text-fill: #555;");

        reportContent.getChildren().addAll(
                title,
                specsBox,
                blueprintBox,
                footer
        );

        ScrollPane scrollPane = new ScrollPane(reportContent);
        scrollPane.setFitToWidth(true);

        Scene scene = new Scene(scrollPane, 800, 700);
        reportStage.setScene(scene);
        reportStage.show();
    }

    private static Image createPlaceholderImage() {
        javafx.scene.canvas.Canvas canvas = new javafx.scene.canvas.Canvas(550, 400);
        javafx.scene.canvas.GraphicsContext gc = canvas.getGraphicsContext2D();
        gc.setFill(javafx.scene.paint.Color.LIGHTGRAY);
        gc.fillRect(0, 0, 550, 400);
        gc.setFill(javafx.scene.paint.Color.BLACK);
        gc.setFont(new javafx.scene.text.Font(18));
        gc.fillText("Blueprint Image Not Available", 180, 200);
        return canvas.snapshot(null, null);
    }
}